from django.conf.urls.defaults import *

urlpatterns = patterns('deal_site.views',
	(r'^$', 'deal'),
	(r'^deal/$', 'deal'),
	(r'^deal/(?P<deal_id>\d+)/$', 'deal'),
	(r'^coupons/$', 'coupons'),
	(r'^verify/$', 'verify'),
	(r'^causes/$', 'causes'),
	(r'^impact/$', 'impact'),
	(r'^community/$', 'community'),
	# (r'^blog/$', 'blog'),
	(r'^login/$', 'login'),
	(r'^thanks/$', 'thanks'),
	(r'^partners/vendors/$', 'partners_vendors'),
	(r'^partners/nonprofits/$', 'partners_nonprofits'),
	(r'^legal/$', 'legal'),
	(r'^press/$', 'press'),
	(r'^jobs/$', 'jobs'),	
)